// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuKsBiBaN0_kZYtT40pAss14NldXs5-M',
    appId: '1:111803032657:web:0ab07eaeb91382a6a64470',
    messagingSenderId: '111803032657',
    projectId: 'mywhatsapp-backend',
    authDomain: 'mywhatsapp-backend.firebaseapp.com',
    storageBucket: 'mywhatsapp-backend.appspot.com',
    measurementId: 'G-JNRTMDECJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdDhmx6KE_pTGW5sWGgCvoiSFXX3Z5-YY',
    appId: '1:111803032657:android:49f157de04e846cba64470',
    messagingSenderId: '111803032657',
    projectId: 'mywhatsapp-backend',
    storageBucket: 'mywhatsapp-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunCMmSMoJr2lTJ4cJ267weXSsW7vG1Nc',
    appId: '1:111803032657:ios:1d8c5f8615ef449ea64470',
    messagingSenderId: '111803032657',
    projectId: 'mywhatsapp-backend',
    storageBucket: 'mywhatsapp-backend.appspot.com',
    iosClientId: '111803032657-kj09g3ihm1kss986ob4oih6jhkffo0r0.apps.googleusercontent.com',
    iosBundleId: 'com.neai.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunCMmSMoJr2lTJ4cJ267weXSsW7vG1Nc',
    appId: '1:111803032657:ios:1d8c5f8615ef449ea64470',
    messagingSenderId: '111803032657',
    projectId: 'mywhatsapp-backend',
    storageBucket: 'mywhatsapp-backend.appspot.com',
    iosClientId: '111803032657-kj09g3ihm1kss986ob4oih6jhkffo0r0.apps.googleusercontent.com',
    iosBundleId: 'com.neai.whatsappClone',
  );
}
